anchor_version = "0.26.0"
solana_version = "1.14.12"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.localnet]
smart_wallet = "smaK3fwkA7ubbxEhsimp1iqPTzfS4MBsNL77QLABZP6"
govern = "GovaE4iu227srtG2s3tZzB4RmWBzw8sTwrCLZz7kN7rY"
voter = "voteXZxajNhmCGpqzBhVArCANMKra5nwqtaaLA6v9CX"
merkle_distributor = "MRKgRBL5XCCT5rwUGnim4yioq9wR4c6rj2EZkw8KdyZ"